# Generated by Django 3.2.8 on 2021-10-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=100)),
                ('car_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tema',
            fields=[
                ('tem_id', models.AutoField(primary_key=True, serialize=False)),
                ('tem_nombre', models.CharField(max_length=100)),
                ('tem_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_username', models.CharField(max_length=50)),
                ('usr_mail', models.CharField(max_length=150)),
                ('usr_pass', models.CharField(max_length=150)),
                ('usr_nombre', models.CharField(max_length=50)),
                ('usr_apellidoPaterno', models.CharField(max_length=50)),
                ('usr_apellidoMaterno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('tra_id', models.AutoField(primary_key=True, serialize=False)),
                ('tra_car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.cargo')),
                ('tra_cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.contrato')),
                ('tra_usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=150)),
                ('pro_tem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.tema')),
            ],
        ),
        migrations.CreateModel(
            name='emprendedor',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='cont_tem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.tema'),
        ),
    ]
