# Generated by Django 3.2.8 on 2021-10-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cont_nombre',
            field=models.CharField(default='Contrato para ToUpApp', max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pro_tem_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toupapi.tema'),
        ),
    ]
