# Generated by Django 3.2.8 on 2021-10-18 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toupapi', '0002_auto_20211018_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='pro_desc',
            field=models.CharField(default='Empresa nueva creada por ToUpApp para emprender', max_length=300),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pro_tem_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='toupapi.tema'),
        ),
    ]
