# Generated by Django 3.2.8 on 2021-10-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toupapi', '0003_auto_20211018_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cont_nombre',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='pro_desc',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pro_users',
            field=models.ManyToManyField(to='toupapi.usuario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pro_tem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupapi.tema'),
        ),
    ]
