# Generated by Django 3.2.8 on 2021-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toupapi', '0004_auto_20211018_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='pro_desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
