# Generated by Django 3.2.8 on 2021-10-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toupapi', '0005_proyecto_pro_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='car_tema',
            field=models.ManyToManyField(to='toupapi.tema'),
        ),
    ]
