# Generated by Django 3.2.8 on 2021-10-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toupapi', '0006_cargo_car_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='tra_cont_id',
        ),
    ]
